<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="IoC\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="IoC\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ProjetoModeloDDD.Infra.Data\ProjetoModeloDDD.Infra.Data.csproj" />
    <ProjectReference Include="..\..\ProjetoModeloDDD.Application\ProjetoModeloDDD.Application.csproj" />
  </ItemGroup>
</Project>
